spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/copy-opgg
    username: sotater
    password: sotater123

application:
  riotApiKey: RGAPI-e0b2c1f4-dc26-4d15-a7fc-6f0410b6146e

api:
  version: v1