spring:
  datasource:
    url: ${COPY_OPGG_DATASOURCE_URL}
    username: ${COPY_OPGG_DATASOURCE_USERNAME}
    password: ${COPY_OPGG_DATASOURCE_PASSWORD}

application:
  riotApiKey: ${RIOT_API_KEY}

api:
  version: v1