spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/copy-opgg
    username: sotater
    password: sotater123

application:
  riotApiKey: RGAPI-f9c89a73-074a-4cc6-88f7-324720b145d5

api:
  version: v1