openapi: 3.0.2
info:
  version: 1.0.0
  title: COPY-OPGG api server
servers:
  - url: 'http://34.69.171.78:80'
    description: 테스트용 GCP 서버
paths:
  /api/summoners/search-by-name/{searchWord}:
    get:
      summary: Search 5 summoner names which start with the searchWord
      operationId: searchByName
      tags:
        - summoners
      parameters:
        - name: searchWord
          in: path
          required: true
          description: word to search
          schema:
            type: string
      responses:
        '200':
          description: summoner names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/summoners'
components:
  schemas:
    summoner:
      required:
        - id
        - name
      properties:
        accountId:
          type: string
        profileIconId:
          type: integer
        revistionDate:
          type: integer
          format: int64
        name:
          type: string
        id:
          type: string
        puuid:
          type: string
        summonerLevel:
          type: integer
          format: int64
    summoners:
      type: array
      items:
        $ref: '#/components/schemas/summoner'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
