openapi: 3.0.2
info:
  version: 1.0.0
  title: COPY-OPGG api server
servers:
  - url: 'http://34.69.171.78:80'
    description: 테스트용 GCP 서버
  - url: 'http://192.168.9.63:8080'
    description: geonho 테스트용 서버
paths:
  /api/summoners/search/auto-complete/{searchWord}:
    get:
      summary: Search 5 summoner names which start with the searchWord
      operationId: searchByName
      tags:
        - summoners
      parameters:
        - name: searchWord
          in: path
          required: true
          description: word to search
          schema:
            type: string
      responses:
        '200':
          description: The brief information of retrived summoners
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summoners'
  /api/summoners/profile-info/{searchWord}:
    get:
      summary: Get profile information of the summoner named searchWord
      operationId: profileInfo
      tags:
        - summoners
      parameters:
        - name: searchWord
          in: path
          required: true
          description: word to search
          schema:
            type: string
      responses:
        '200':
          description: summoner profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummonerBriefInfo'
components:
  schemas:
    SummonerBriefInfo:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        summonerLevel:
          type: integer
          format: int64
        profileIconId:
          type: integer
        leagueInfo:
          $ref: '#/components/schemas/SummonerLeagueInfo'
    SummonerLeagueInfo:
      required:
        - leagueId
        - tier
        - rank
        - leaguePoints
      properties:
        leagueId:
          type: string
        tier:
          $ref: '#/components/schemas/Tier'
        rank:
          $ref: '#/components/schemas/Rank'
        leaguePoints:
          type: integer
          format: int32
    Tier:
      type: string
      enum:
        - DIAMOND
        - PLATINUM
        - GOLD
        - SILVER
        - BRONZE
        - IRON
    Rank:
      type: string
      enum:
        - I
        - II
        - III
        - IV
    Summoners:
      type: array
      items:
        $ref: '#/components/schemas/SummonerBriefInfo'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
